### ISSUE TITLE
But then no one will fix the problem with existing code

### ISSUE THREAD

**Issue by jitendravyas** [rstacruz/stylelint-disable-all#1]

**Comment by rstacruz** [comment]
Thanks for the report, but this seems like an issue outside the bounds of the project's jurisdiction, and there's nothing stylelint-disable-all can do to help that.

The best approach is to fix the errors all in one go, and this tool is a stop-gap for when that's not possible. The next best approach is to use stylelint-disable-all, then schedule to fix code every now and then.

IMHO though, it's actually _alright_ if no one will fix the problem. You can treat your old code as a black-box, the same way you would treat npm packages or ruby gems. While it's not the best solution, it's bounds better than not having linting at all.
